#define TK_SELECT                        1
#define TK_FROM                          2
#define TK_WHERE                         3
#define TK_GROUP                         4
#define TK_BY                            5
#define TK_HAVING                        6
#define TK_ORDER                         7
#define TK_LIMIT                         8
#define TK_OFFSET                        9
#define TK_ASC                          10
#define TK_DESC                         11
#define TK_DISTINCT                     12
#define TK_ALL                          13
#define TK_UNION                        14
#define TK_INTERSECT                    15
#define TK_EXCEPT                       16
#define TK_INSERT                       17
#define TK_INTO                         18
#define TK_VALUES                       19
#define TK_DEFAULT                      20
#define TK_REPLACE                      21
#define TK_UPDATE                       22
#define TK_SET                          23
#define TK_DELETE                       24
#define TK_CREATE                       25
#define TK_TABLE                        26
#define TK_INDEX                        27
#define TK_VIEW                         28
#define TK_TRIGGER                      29
#define TK_TEMP                         30
#define TK_TEMPORARY                    31
#define TK_ALTER                        32
#define TK_RENAME                       33
#define TK_DROP                         34
#define TK_IF                           35
#define TK_NOT                          36
#define TK_EXISTS                       37
#define TK_PRAGMA                       38
#define TK_BEGIN                        39
#define TK_COMMIT                       40
#define TK_END                          41
#define TK_ROLLBACK                     42
#define TK_TRANSACTION                  43
#define TK_SAVEPOINT                    44
#define TK_RELEASE                      45
#define TK_ATTACH                       46
#define TK_DETACH                       47
#define TK_DATABASE                     48
#define TK_AS                           49
#define TK_AND                          50
#define TK_OR                           51
#define TK_NULL                         52
#define TK_TRUE                         53
#define TK_FALSE                        54
#define TK_PRIMARY                      55
#define TK_KEY                          56
#define TK_UNIQUE                       57
#define TK_FOREIGN                      58
#define TK_REFERENCES                   59
#define TK_CHECK                        60
#define TK_AUTOINCR                     61
#define TK_ON                           62
#define TK_USING                        63
#define TK_IN                           64
#define TK_LIKE                         65
#define TK_BETWEEN                      66
#define TK_IS                           67
#define TK_CASE                         68
#define TK_WHEN                         69
#define TK_THEN                         70
#define TK_ELSE                         71
#define TK_EXPLAIN                      72
#define TK_QUERY                        73
#define TK_PLAN                         74
#define TK_WITH                         75
#define TK_RECURSIVE                    76
#define TK_TO                           77
#define TK_JOIN                         78
#define TK_INNER                        79
#define TK_OUTER                        80
#define TK_LEFT                         81
#define TK_RIGHT                        82
#define TK_FULL                         83
#define TK_CROSS                        84
#define TK_NATURAL                      85
#define TK_CAST                         86
#define TK_LP                           87
#define TK_RP                           88
#define TK_COMMA                        89
#define TK_SEMI                         90
#define TK_DOT                          91
#define TK_STAR                         92
#define TK_PLUS                         93
#define TK_MINUS                        94
#define TK_SLASH                        95
#define TK_PERCENT                      96
#define TK_EQ                           97
#define TK_NE                           98
#define TK_LT                           99
#define TK_LE                          100
#define TK_GT                          101
#define TK_GE                          102
#define TK_CONCAT                      103
#define TK_AMP                         104
#define TK_PIPE                        105
#define TK_QMARK                       106
#define TK_TILDE                       107
#define TK_ID                          108
#define TK_NUMBER                      109
#define TK_STRING                      110
#define TK_BLOB                        111
#define TK_UMINUS                      112
