/* DO NOT EDIT: automatically built by dist/s_include. */
/* See M0_CLAIMS.md [T2]. */

#ifndef OS_EXT_H
#define OS_EXT_H

int (*__os_errno_get_hook __P((void)))(int);
int __os_aligned_alloc __P((size_t, size_t, void **));
int __os_alloc_get_hook __P((struct __os_alloc_hook *));
int __os_alloc_set_hook __P((const struct __os_alloc_hook *));
int __os_backtrace __P((void **, int));
int __os_backtrace_supported __P((void));
int __os_call_once __P((__os_once_t *, void (*)(void)));
int __os_calloc __P((size_t, size_t, void **));
int __os_clock_mono __P((int64_t *));
int __os_clock_real __P((int64_t *));
int __os_cond_broadcast __P((__os_cond_t *));
int __os_cond_destroy __P((__os_cond_t *));
int __os_cond_init __P((__os_cond_t *));
int __os_cond_signal __P((__os_cond_t *));
int __os_cond_wait __P((__os_cond_t *, __os_mutex_t *));
int __os_crypto_aes_gcm_decrypt __P((const uint8_t *, const uint8_t *, const void *, size_t, const void *, size_t, const uint8_t *, void *));
int __os_crypto_aes_gcm_encrypt __P((const uint8_t *, const uint8_t *, const void *, size_t, const void *, size_t, void *, uint8_t *));
int __os_crypto_blake3 __P((const void *, size_t, uint8_t *));
int __os_crypto_chacha20_poly1305_decrypt __P((const uint8_t *, const uint8_t *, const void *, size_t, const void *, size_t, const uint8_t *, void *));
int __os_crypto_chacha20_poly1305_encrypt __P((const uint8_t *, const uint8_t *, const void *, size_t, const void *, size_t, void *, uint8_t *));
int __os_crypto_hkdf __P((const void *, size_t, const void *, size_t, const void *, size_t, void *, size_t));
int __os_crypto_hkdf_expand __P((const uint8_t *, const void *, size_t, void *, size_t));
int __os_crypto_hkdf_extract __P((const void *, size_t, const void *, size_t, uint8_t *));
int __os_crypto_hmac_sha256 __P((const void *, size_t, const void *, size_t, uint8_t *));
int __os_crypto_sha256 __P((const void *, size_t, uint8_t *));
int __os_crypto_sha3_256 __P((const void *, size_t, uint8_t *));
int __os_crypto_sha3_512 __P((const void *, size_t, uint8_t *));
int __os_csprng_bytes __P((__os_csprng_t *, void *, size_t));
int __os_csprng_init __P((__os_csprng_t **));
int __os_env_get __P((const char *, char *, size_t));
int __os_env_set __P((const char *, const char *, int));
int __os_errno_map __P((int));
int __os_malloc __P((size_t, void **));
int __os_mutex_destroy __P((__os_mutex_t *));
int __os_mutex_init __P((__os_mutex_t *));
int __os_mutex_lock __P((__os_mutex_t *));
int __os_mutex_trylock __P((__os_mutex_t *));
int __os_mutex_unlock __P((__os_mutex_t *));
int __os_ncpus __P((void));
int __os_ncpus_effic __P((void));
int __os_ncpus_perf __P((void));
int __os_numa_current_node __P((void));
int __os_numa_nnodes __P((void));
int __os_numa_node_of_cpu __P((int));
int __os_pthread_create_masked __P((pthread_t *, void *(*)(void *), void *));
int __os_realloc __P((void *, size_t, void **));
int __os_rwlock_destroy __P((__os_rwlock_t *));
int __os_rwlock_init __P((__os_rwlock_t *));
int __os_rwlock_rdlock __P((__os_rwlock_t *));
int __os_rwlock_rdunlock __P((__os_rwlock_t *));
int __os_rwlock_wrlock __P((__os_rwlock_t *));
int __os_rwlock_wrunlock __P((__os_rwlock_t *));
int __os_sem_destroy __P((__os_sem_t *));
int __os_sem_init __P((__os_sem_t *, unsigned));
int __os_sem_post __P((__os_sem_t *));
int __os_sem_trywait __P((__os_sem_t *));
int __os_sem_wait __P((__os_sem_t *));
int __os_sleep_ns __P((int64_t));
int __os_strdup __P((const char *, char **));
int __os_thread_atexit __P((void (*)(void *), void *));
int __os_thread_create __P((__os_thread_t *, __os_thread_fn, void *));
int __os_thread_detach __P((__os_thread_t *));
int __os_thread_join __P((__os_thread_t *, void **));
int __os_thread_self __P((__os_thread_t *));
int __os_thread_set_affinity __P((int));
int __os_thread_setname __P((const char *));
int __os_tls_create __P((__os_tls_key_t *, __os_tls_dtor));
int __os_tls_destroy __P((__os_tls_key_t));
int __os_tls_set __P((__os_tls_key_t, void *));
int __xtc_dio_is_direct __P((int));
int xtc_fs_close __P((int));
int xtc_fs_dio_align __P((int, size_t *, size_t *, size_t *));
int xtc_fs_dio_alloc __P((int, size_t, void **));
int xtc_fs_dir_next __P((xtc_fs_dir_t *, const char **));
int xtc_fs_dir_open __P((const char *, xtc_fs_dir_t **));
int xtc_fs_exists __P((const char *));
int xtc_fs_fdatasync __P((int));
int xtc_fs_fsize __P((int, int64_t *));
int xtc_fs_fsync __P((int));
int xtc_fs_ftruncate __P((int, int64_t));
int xtc_fs_mkdir __P((const char *));
int xtc_fs_mkstemp __P((char *, int *));
int xtc_fs_open __P((const char *, uint32_t, int *));
int xtc_fs_pread __P((int, void *, size_t, int64_t, size_t *));
int xtc_fs_pwrite __P((int, const void *, size_t, int64_t, size_t *));
int xtc_fs_rename __P((const char *, const char *));
int xtc_fs_rmdir __P((const char *));
int xtc_fs_stat __P((const char *, xtc_fs_stat_t *));
int xtc_fs_tmpdir __P((char *, size_t));
int xtc_fs_unlink __P((const char *));
int64_t __os_mem_max __P((void));
size_t __os_msize __P((void *));
size_t __os_strlcat __P((char *, const char *, size_t));
size_t __os_strlcpy __P((char *, const char *, size_t));
uint64_t __os_rand_u64 __P((void));
void *__os_tls_get __P((__os_tls_key_t));
void __os_aligned_free __P((void *));
void __os_backtrace_emit __P((int, void *const *, int));
void __os_csprng_destroy __P((__os_csprng_t *));
void __os_errno_set_hook __P((int (*)(int)));
void __os_free __P((void *));
void __os_rand_seed __P((uint64_t));
void __os_thread_apply_default_qos __P((void));
void __os_thread_yield __P((void));
void xtc_fs_dio_free __P((void *));
void xtc_fs_dir_close __P((xtc_fs_dir_t *));

#endif /* OS_EXT_H */
