/* DO NOT EDIT: automatically built by dist/s_include. */
/* See M0_CLAIMS.md [T2]. */

#ifndef PTC_EXT_H
#define PTC_EXT_H

int   xtc_proc_set_class __P((xtc_exec_class_t));
int   xtc_proc_set_userdata __P((void *));
int  xtc_cfg_load_file __P((const char *));
int  xtc_cfg_reload __P((void));
int  xtc_dispatch __P((xtc_loop_t *, int (*)(void *), void *, xtc_future_t **, xtc_dispatch_handle_t **));
int  xtc_dispatch_cancel __P((xtc_dispatch_handle_t *));
int __xtc_proc_crit_depth __P((void));
int __xtc_unsafe_depth __P((void));
int xtc_aio_fdatasync __P((int));
int xtc_aio_fsync __P((int));
int xtc_aio_pread __P((int, void *, uint32_t, int64_t));
int xtc_aio_preadv __P((int, const struct iovec *, int, int64_t));
int xtc_aio_pwrite __P((int, const void *, uint32_t, int64_t));
int xtc_aio_pwritev __P((int, const struct iovec *, int, int64_t));
int xtc_alloc_audit_enable __P((int));
int xtc_blocking_run_off_loop __P((int (*)(void *), void *, int *));
int xtc_blocking_submit __P((int (*)(void *), void *));
int xtc_bracket __P((int (*)(void **, void *), int (*)(void *, void *), void (*)(void *, void *), void *));
int xtc_cancel_poll __P((int (*)(void *), void *));
int xtc_cancel_requested __P((void));
int xtc_crash_handler_install __P((void));
int xtc_down_decode __P((const void *, size_t, xtc_pid_t *, int *));
int xtc_down_decode_ex __P((const void *, size_t, xtc_down_info_t *));
int xtc_exit_pid __P((xtc_pid_t, int));
int xtc_exit_self __P((int));
int xtc_fault_guard_install __P((void));
int xtc_inject_check __P((const char *));
int xtc_link __P((xtc_pid_t));
int xtc_monitor __P((xtc_pid_t, uint64_t *));
int xtc_preempt_arm __P((int64_t));
int xtc_preempt_disarm __P((void));
int xtc_preempt_supported __P((void));
int xtc_preempt_tick_pending __P((void));
int xtc_proc_at_exit __P((void (*)(void *), void *));
int xtc_proc_mailbox_stats __P((xtc_pid_t, xtc_mailbox_stats_t *));
int xtc_proc_recovery_track __P((void (*)(void *), void *));
int xtc_proc_recovery_track_fd __P((int));
int xtc_proc_recovery_track_locks __P((void *, uint64_t, void (*)(void *, uint64_t)));
int xtc_proc_recovery_track_mctx __P((struct xtc_mctx *));
int xtc_proc_recovery_untrack_fd __P((int));
int xtc_proc_sleep __P((int64_t));
int xtc_proc_spawn __P((xtc_loop_t *, xtc_proc_fn, void *, const xtc_proc_opts_t *, xtc_pid_t *));
int xtc_proc_spawn_link __P((xtc_loop_t *, xtc_proc_fn, void *, const xtc_proc_opts_t *, xtc_pid_t *));
int xtc_proc_spawn_monitor __P((xtc_loop_t *, xtc_proc_fn, void *, const xtc_proc_opts_t *, xtc_pid_t *, uint64_t *));
int xtc_proc_wait_fd __P((int, uint32_t, int64_t, uint32_t *));
int xtc_proc_wake __P((xtc_pid_t));
int xtc_recv __P((void **, size_t *, int64_t));
int xtc_recv_correlate __P((const void *, size_t, int, xtc_msg_t *, int *, int64_t));
int xtc_recv_match __P((xtc_match_fn, void *, void **, size_t *, int64_t));
int xtc_res_acquire __P((xtc_res_t *, xtc_res_kind_t, int64_t));
int xtc_res_init __P((xtc_res_t *, const xtc_res_caps_t *));
int xtc_res_set_alert __P((xtc_res_t *, xtc_res_kind_t, double));
int xtc_res_set_alert_fn __P((xtc_res_t *, void (*)(xtc_res_kind_t, int64_t, int64_t, void *), void *));
int xtc_scope_defer __P((xtc_scope_t *, xtc_finalizer_fn, void *));
int xtc_send __P((xtc_pid_t, const void *, size_t));
int xtc_trace_causal_dump __P((xtc_pid_t, xtc_causal_fn, void *));
int xtc_trace_causal_enable __P((int));
int xtc_uncancelable __P((int (*)(void *), void *));
int xtc_unlink __P((xtc_pid_t));
int64_t xtc_res_high __P((const xtc_res_t *, xtc_res_kind_t));
int64_t xtc_res_rejects __P((const xtc_res_t *, xtc_res_kind_t));
int64_t xtc_res_used __P((const xtc_res_t *, xtc_res_kind_t));
long xtc_lwlock_track_violations __P((void));
struct xtc_mctx *xtc_proc_mctx __P((void));
uint64_t xtc_preempt_ticks __P((void));
void  __xtc_proc_ctx_restore __P((void *));
void *__xtc_proc_ctx_save __P((void));
void *xtc_proc_userdata __P((void));
void __xtc_unsafe_enter __P((void));
void __xtc_unsafe_leave __P((void));
void xtc_alloc_audit_proc_leaks __P((xtc_pid_t, size_t *, size_t *));
void xtc_alloc_audit_stats __P((size_t *, size_t *));
void xtc_dispatch_handle_free __P((xtc_dispatch_handle_t *));
void xtc_dump __P((int));
void xtc_lwlock_track_enable __P((int));
void xtc_lwlock_track_reset __P((void));
void xtc_lwlock_track_set_handler __P((xtc_lwlock_track_fn, void *));
void xtc_panic __P((const char *, int, const char *, ...));
void xtc_preempt_set_involuntary __P((int));
void xtc_proc_critical_enter __P((void));
void xtc_proc_critical_leave __P((void));
void xtc_proc_recovery_cleanup __P((void));
void xtc_proc_recovery_disarm __P((void));
void xtc_res_release __P((xtc_res_t *, xtc_res_kind_t, int64_t));
void xtc_res_set_cap __P((xtc_res_t *, xtc_res_kind_t, int64_t));
void xtc_scope_close __P((xtc_scope_t *));
void xtc_tuning_check __P((void));
xtc_pid_t xtc_self __P((void));
xtc_scope_t *xtc_scope_open __P((void));

#endif /* PTC_EXT_H */
